
# Site settings
title: Zebin You
name: Zebin You
subtitle:  Phd
email: zebin
description: >
   Phd
baseurl: ""
url: "https://yyyouy.github.io/"
github_username:  yyyouy
disqus_baseurl: "https://yyyouy.github.io/"
disqus_shortname: https-yyyouy-github-io
permalink: :title
google-site-verification: ""

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Zebin You"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: yyyouy
    url: https://github.com/yyyouy
    desc: Fork me on GitHub
    share: false

  
